/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "services.website": [],
    "services.software": [],
    "services.marketing": [],
    "services": [],
    "about-us": [],
    "blog": [],
    "contact-us": [],
    "contact-us.post": [],
    "dashboard": [],
    "contactusdata": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.update": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": []
}
}
export {};
